//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusCard
    {
        public int BonusCardId { get; set; }
        public string Number { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public int CustomerId { get; set; }
        public int BonusCardLevelId { get; set; }
    
        public virtual BonusCardLevel BonusCardLevel { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
