//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusCard
    {
        public int BonusCardId { get; set; }
        public string Number { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public int CustomerId { get; set; }
        public int BonusCardLevelId { get; set; }
    
        public virtual BonusCardLevel BonusCardLevel { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
