//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTag
    {
        public int CustomerTagId { get; set; }
        public int CustomerId { get; set; }
        public int TagId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
