//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginHistoryId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoginDatetime { get; set; }
        public Nullable<System.DateTime> ExitDatetime { get; set; }
    
        public virtual User User { get; set; }
    }
}
