//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrder()
        {
            this.SaleOrderContent = new HashSet<SaleOrderContent>();
        }
    
        public int SaleOrderId { get; set; }
        public int CustomerId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> TargetDeliveryDate { get; set; }
        public Nullable<System.DateTime> StartDeliveryDate { get; set; }
        public Nullable<System.DateTime> EndDeliveryDate { get; set; }
        public string Address { get; set; }
        public string ContactPhone { get; set; }
        public int StatusId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderContent> SaleOrderContent { get; set; }
    }
}
