//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderContent
    {
        public int SaleOrderContentId { get; set; }
        public int SaleOrderId { get; set; }
        public int WarehouseUnitId { get; set; }
        public int Amount { get; set; }
    
        public virtual SaleOrder SaleOrder { get; set; }
        public virtual WarehouseUnit WarehouseUnit { get; set; }
    }
}
