//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderContent
    {
        public int SaleOrderContentId { get; set; }
        public int SaleOrderId { get; set; }
        public int WarehouseUnitId { get; set; }
        public int Amount { get; set; }
    
        public virtual SaleOrder SaleOrder { get; set; }
        public virtual WarehouseUnit WarehouseUnit { get; set; }
    }
}
