//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrder
    {
        public int SupplyOrderId { get; set; }
        public int SupplierId { get; set; }
        public int WarehouseUnitId { get; set; }
        public int Amount { get; set; }
        public decimal PricePerProduct { get; set; }
        public Nullable<System.DateTime> DeliveryStartDate { get; set; }
        public Nullable<System.DateTime> DeliveryEndDate { get; set; }
        public int EmployeeId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual WarehouseUnit WarehouseUnit { get; set; }
    }
}
