//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrder
    {
        public int SupplyOrderId { get; set; }
        public int SupplierId { get; set; }
        public int WarehouseUnitId { get; set; }
        public int Amount { get; set; }
        public decimal PricePerProduct { get; set; }
        public Nullable<System.DateTime> DeliveryStartDate { get; set; }
        public Nullable<System.DateTime> DeliveryEndDate { get; set; }
        public int EmployeeId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual WarehouseUnit WarehouseUnit { get; set; }
        public virtual User User { get; set; }
    }
}
