//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseUnit()
        {
            this.SaleOrderContent = new HashSet<SaleOrderContent>();
            this.SupplyOrder = new HashSet<SupplyOrder>();
        }
    
        public int WarehouseUnitId { get; set; }
        public int ProductId { get; set; }
        public int Amount { get; set; }
        public int MinimalAmount { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderContent> SaleOrderContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyOrder> SupplyOrder { get; set; }
    }
}
